### ISSUE TITLE
Unable to install with `go get`

### ISSUE THREAD

**Issue by jcbwlkr** [relops/cqlc#22]
This tool looks great and I would love to use it. When I try install it I get compilation errors. I'm not sure if I'm doing something wrong or what. In this example I made a new empty `$GOPATH` to be sure there was not some weird dependency issue.

    ~ ᐳ rm -rf tmp
    ~ ᐳ mkdir tmp
    ~ ᐳ export GOPATH=$PWD/tmp
    ~ ᐳ cd $GOPATH
    ~/tmp ᐳ ls
    ~/tmp ᐳ go get github.com/relops/cqlc
    # github.com/relops/cqlc/generator
    src/github.com/relops/cqlc/generator/generator.go:165: t.Type undefined (type *gocql.TypeInfo has no field or method Type)
    src/github.com/relops/cqlc/generator/generator.go:175: invalid case gocql.TypeList in switch on t.Type (mismatched types int and func() gocql.Type)
    src/github.com/relops/cqlc/generator/generator.go:175: invalid case gocql.TypeSet in switch on t.Type (mismatched types int and func() gocql.Type)
    src/github.com/relops/cqlc/generator/generator.go:176: t.Elem undefined (type gocql.TypeInfo has no field or method Elem)
    src/github.com/relops/cqlc/generator/generator.go:177: invalid case gocql.TypeMap in switch on t.Type (mismatched types int and func() gocql.Type)
    src/github.com/relops/cqlc/generator/generator.go:178: t.Key undefined (type gocql.TypeInfo has no field or method Key)
    src/github.com/relops/cqlc/generator/generator.go:179: t.Elem undefined (type gocql.TypeInfo has no field or method Elem)
    src/github.com/relops/cqlc/generator/template.go:46: invalid operation: c.Type.Type == gocql.TypeCounter (mismatched types func() gocql.Type and int)
    src/github.com/relops/cqlc/generator/template.go:71: invalid operation: c.Type.Type == gocql.TypeList (mismatched types func() gocql.Type and int)
    src/github.com/relops/cqlc/generator/template.go:71: invalid operation: c.Type.Type == gocql.TypeSet (mismatched types func() gocql.Type and int)
    src/github.com/relops/cqlc/generator/template.go:71: too many errors

Do you have any advice?

**Comment by 0x6e6562** [comment]
Unfortunately what has happened is that the upstream API (i.e. gocql) has landed a breaking change in the last fortnight which hasn't yet been pulled straight in cqlc. To compound this, I made the decision a while back not to pin the dependency on a specific gocql version, because this would make an assumption that an end user might not like. So the only two options are:

1. For me to hurry up and pull the changes straight
2. To update gocql to an earlier version

I think the best solution is (1).

I'll try to get this done ASAP.

**Comment by jcbwlkr** [comment]
@0x6e6562 ah I see. Thanks for looking in to this and let me know if I can help somehow.

**Comment by 0x6e6562** [comment]
This issue was auto-closed by #23, but I'm re-opening to get your confirmation that this indeed fixes the issue you are seeing.

**Comment by jcbwlkr** [comment]
Looks good. Thanks! (^_^)
