### ISSUE TITLE
Compilation failure with new gocql driver

### ISSUE THREAD

**Issue by kchugalinskiy** [relops/cqlc#38]
# github.com/relops/cqlc/generator
../gocode/src/github.com/relops/cqlc/generator/template.go:50: undefined: gocql.CLUSTERING_KEY
../gocode/src/github.com/relops/cqlc/generator/template.go:54: undefined: gocql.PARTITION_KEY
../gocode/src/github.com/relops/cqlc/generator/template.go:59: undefined: gocql.PARTITION_KEY
../gocode/src/github.com/relops/cqlc/generator/template.go:62: undefined: gocql.CLUSTERING_KEY
../gocode/src/github.com/relops/cqlc/generator/template.go:85: undefined: gocql.CLUSTERING_KEY
../gocode/src/github.com/relops/cqlc/generator/template.go:91: undefined: gocql.PARTITION_KEY

**Comment by ddave09** [comment]
I believe this is the same issue as issue #36. Fix has already been committed and pull request has been generated. If you agree please close the issue.

**Comment by kchugalinskiy** [comment]
@ddave09 thank you!

**Comment by gevgev** [comment]
Hi. 
I am seeing same issue, not sure if the above mentioned fix already committed:

$ go get github.com/relops/cqlc
# github.com/relops/cqlc/generator
../../../relops/cqlc/generator/template.go:50: undefined: gocql.CLUSTERING_KEY
../../../relops/cqlc/generator/template.go:54: undefined: gocql.PARTITION_KEY
../../../relops/cqlc/generator/template.go:59: undefined: gocql.PARTITION_KEY
../../../relops/cqlc/generator/template.go:62: undefined: gocql.CLUSTERING_KEY
../../../relops/cqlc/generator/template.go:85: undefined: gocql.CLUSTERING_KEY
../../../relops/cqlc/generator/template.go:91: undefined: gocql.PARTITION_KEY

**Comment by ddave09** [comment]
It is already committed. Look at the pull request of 20th December. It has not been merged to the main branch and I don't have access to do that either. It works on my machine. If you want clone it from my fork
https://github.com/ddave09/cqlc until it gets merged. Travis CI has failed and hence I guess it's not merged yet.

**Comment by gevgev** [comment]
Yes, I forked and pulled that commit. Thanks. Confirming - it works.

**Comment by kchugalinskiy** [comment]
I confirms, it works 100% for me

**Comment by jeffatuber** [comment]
I am still getting this issue today.

**Comment by jeffdh5** [comment]
Trying to install cqlc but still failing at the same issue. The fork failed as well.

**Comment by lianqiao** [comment]
@jeffdh5 @gevgev , I solved this by overwriting the relops directory with ddave09 manually, just remove relops and rename ddave09 to relops

**Comment by tanmay-saha** [comment]
@lianqiao this worked for me as well. Can somebody get someone involved in merging the changes in the main relops repo? I see this thread itself is so long.
